name: test
on: push
jobs: 
  test: 
    runs-on: ubuntu-22.04 
    container: osrf/ros:humble-desktop-full
    steps:
      - uses: actions/checkout@v2
      - name: apt update
        run: |
          sudo apt update -y
      - name: build
        run: | 
          rsync -av ./ /root/ros2_ws/src/emcl2_ros2/
          cd /root/ros2_ws
          source /opt/ros/$ROS_DISTRO/setup.bash
          rosdep update
          rosdep install -i -y --from-path src --rosdistro $ROS_DISTRO
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
        shell: bash
      - name: exec
        run: |
          source /root/ros2_ws/install/setup.bash
          ros2 run emcl2 test.bash
        shell: bash
        

          